service: aura-checkout-service
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  versionFunctions: false # optional, default is true
  tracing:
    lambda: true # optional, enables tracing for all functions (can be true (true equals 'Active') 'Active' or 'PassThrough')
  # vpc:
  #   securityGroupIds:
  #     - sg-0beb51425da9b2751
  #   subnetIds:
  #     - subnet-d13443ab
  #     - subnet-ed54eea1
  #     - subnet-065d766f
# add 5 function for CURD operation
functions:
  bridge:
    handler: index.app
    events:
      - http:
          path: /{any+}
          method: any
          cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
